# Generated by Django 5.1.6 on 2025-02-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truefalsequestion',
            old_name='answer',
            new_name='_answer',
        ),
    ]
